// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.Robot2015UpdatedProgram;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Victor;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainleftFrontMotorController;
    public static SpeedController drivetrainleftRearMotorController;
    public static SpeedController drivetrainrightRearMotorController;
    public static SpeedController drivetrainrightFrontMotorController;
    public static RobotDrive drivetrainRobotDrive41;
    public static SpeedController pulleypulleyMotorController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainleftFrontMotorController = new Victor(2);
        LiveWindow.addActuator("Drivetrain", "leftFrontMotorController", (Victor) drivetrainleftFrontMotorController);
        
        drivetrainleftRearMotorController = new Talon(1);
        LiveWindow.addActuator("Drivetrain", "leftRearMotorController", (Talon) drivetrainleftRearMotorController);
        
        drivetrainrightRearMotorController = new Talon(0);
        LiveWindow.addActuator("Drivetrain", "rightRearMotorController", (Talon) drivetrainrightRearMotorController);
        
        drivetrainrightFrontMotorController = new Talon(3);
        LiveWindow.addActuator("Drivetrain", "rightFrontMotorController", (Talon) drivetrainrightFrontMotorController);
        
        drivetrainRobotDrive41 = new RobotDrive(drivetrainleftFrontMotorController, drivetrainleftRearMotorController,
              drivetrainrightFrontMotorController, drivetrainrightRearMotorController);
        
        drivetrainRobotDrive41.setSafetyEnabled(true);
        drivetrainRobotDrive41.setExpiration(0.1);
        drivetrainRobotDrive41.setSensitivity(0.5);
        drivetrainRobotDrive41.setMaxOutput(1.0);

        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        pulleypulleyMotorController = new Jaguar(4);
        LiveWindow.addActuator("Pulley", "pulleyMotorController", (Jaguar) pulleypulleyMotorController);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
